name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: t10&#45;01&#45;01
      id: t10-45-01-45-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t10&#45;01&#45;01
        setup-command: make compile
        command: make -s test_01
        input: dorm-print-all-detail\r\nstudent-print-all-detail\r\n---\r\n
        expected-output: Antiokia|5|male|0\r\nMamre|5|male|0\r\nSilo|5|male|0\r\nMahanaim|5|male|0\r\nNazaret|5|male|0\r\n12S21001|Dhino
          Turnip|2021|male|unassigned\r\n12S21002|Marudut Tampubolon|2021|male|unassigned\r\n12S21003|Jusas
          Tampubolon|2021|male|unassigned\r\n12S21004|Estomihi pangaribuan|2021|male|unassigned\r\n12S21006|Weny
          Sitinjak|2021|female|unassigned\r\n
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: t10&#45;01&#45;02
      id: t10-45-01-45-02
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t10&#45;01&#45;02
        setup-command: make compile
        command: make -s test_01
        input: student-add#12S21007#Dame Sitinjak#2021#female\r\nstudent-add#12S21008#Tuani
          Manurung#2021#male\r\nstudent-add#12S21009#Mikhael Pakpahan#2021#male\r\nstudent-add#12S21010#Bobby
          Siagian#2021#male\r\nstudent-add#12S21011#Aldi Simamora#2021#male\r\nstudent-print-all\r\ndorm-add#Pniel#20#female\r\ndorm-add#Kapernaum#20#male\r\ndorm-print-all\r\nstudent-print-all-detail\r\ndorm-print-all-detail\r\n---\r\n
        expected-output: 12S21001|Dhino Turnip|2021|male\r\n12S21002|Marudut Tampubolon|2021|male\r\n12S21003|Jusas
          Tampubolon|2021|male\r\n12S21004|Estomihi pangaribuan|2021|male\r\n12S21006|Weny
          Sitinjak|2021|female\r\n12S21007|Dame Sitinjak|2021|female\r\n12S21008|Tuani
          Manurung|2021|male\r\n12S21009|Mikhael Pakpahan|2021|male\r\n12S21010|Bobby
          Siagian|2021|male\r\n12S21011|Aldi Simamora|2021|male\r\nAntiokia|5|male\r\nMamre|5|male\r\nSilo|5|male\r\nMahanaim|5|male\r\nNazaret|5|male\r\nPniel|20|female\r\nKapernaum|20|male\r\n12S21001|Dhino
          Turnip|2021|male|unassigned\r\n12S21002|Marudut Tampubolon|2021|male|unassigned\r\n12S21003|Jusas
          Tampubolon|2021|male|unassigned\r\n12S21004|Estomihi pangaribuan|2021|male|unassigned\r\n12S21006|Weny
          Sitinjak|2021|female|unassigned\r\n12S21007|Dame Sitinjak|2021|female|unassigned\r\n12S21008|Tuani
          Manurung|2021|male|unassigned\r\n12S21009|Mikhael Pakpahan|2021|male|unassigned\r\n12S21010|Bobby
          Siagian|2021|male|unassigned\r\n12S21011|Aldi Simamora|2021|male|unassigned\r\nAntiokia|5|male|0\r\nMamre|5|male|0\r\nSilo|5|male|0\r\nMahanaim|5|male|0\r\nNazaret|5|male|0\r\nPniel|20|female|0\r\nKapernaum|20|male|0\r\n
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: t10&#45;02&#45;01
      id: t10-45-02-45-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t10&#45;02&#45;01
        setup-command: make compile
        command: make -s test_02
        input: student-add#12S21007#Dame Sitinjak#2021#female\r\nstudent-add#12S21008#Tuani
          Manurung#2021#male\r\nstudent-print-all\r\ndorm-add#Pniel#20#female\r\ndorm-add#Kapernaum#20#male\r\ndorm-print-all\r\nstudent-print-all-detail\r\ndorm-print-all-detail\r\nstudent-add#12S21009#Mikhael
          Pakpahan#2021#male\r\nstudent-add#12S21010#Bobby Siagian#2021#male\r\nstudent-add#12S21011#Aldi
          Simamora#2021#male\r\n---\r\n
        expected-output: 12S21001|Dhino Turnip|2021|male\r\n12S21002|Marudut Tampubolon|2021|male\r\n12S21003|Jusas
          Tampubolon|2021|male\r\n12S21004|Estomihi pangaribuan|2021|male\r\n12S21006|Weny
          Sitinjak|2021|female\r\n12S21007|Dame Sitinjak|2021|female\r\n12S21008|Tuani
          Manurung|2021|male\r\n12S21009|Mikhael Pakpahan|2021|male\r\n12S21010|Bobby
          Siagian|2021|male\r\n12S21011|Aldi Simamora|2021|male\r\n12S21007|Dame Sitinjak|2021|female\r\n12S21008|Tuani
          Manurung|2021|male\r\nAntiokia|5|male\r\nMamre|5|male\r\nSilo|5|male\r\nMahanaim|5|male\r\nNazaret|5|male\r\nPniel|20|female\r\nKapernaum|20|male\r\nPniel|20|female\r\nKapernaum|20|male\r\n12S21001|Dhino
          Turnip|2021|male|unassigned\r\n12S21002|Marudut Tampubolon|2021|male|unassigned\r\n12S21003|Jusas
          Tampubolon|2021|male|unassigned\r\n12S21004|Estomihi pangaribuan|2021|male|unassigned\r\n12S21006|Weny
          Sitinjak|2021|female|unassigned\r\n12S21007|Dame Sitinjak|2021|female|unassigned\r\n12S21008|Tuani
          Manurung|2021|male|unassigned\r\n12S21009|Mikhael Pakpahan|2021|male|unassigned\r\n12S21010|Bobby
          Siagian|2021|male|unassigned\r\n12S21011|Aldi Simamora|2021|male|unassigned\r\n12S21007|Dame
          Sitinjak|2021|female|unassigned\r\n12S21008|Tuani Manurung|2021|male|unassigned\r\nAntiokia|5|male|0\r\nMamre|5|male|0\r\nSilo|5|male|0\r\nMahanaim|5|male|0\r\nNazaret|5|male|0\r\nPniel|20|female|0\r\nKapernaum|20|male|0\r\nPniel|20|female|0\r\nKapernaum|20|male|0\r\n
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: t10&#45;02&#45;02
      id: t10-45-02-45-02
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t10&#45;02&#45;02
        setup-command: make compile
        command: make -s test_02
        input: student-add#12S21008#Tuani Manurung#2021#male\r\nstudent-add#12S21007#Dame
          Sitinjak#2021#female\r\nstudent-print-all\r\ndorm-add#Pniel#20#female\r\ndorm-add#Kapernaum#20#male\r\ndorm-print-all\r\nstudent-add#12S21009#Mikhael
          Pakpahan#2021#male\r\nstudent-add#12S21010#Bobby Siagian#2021#male\r\nstudent-add#12S21011#Aldi
          Simamora#2021#male\r\nassign-student#12S21001#Antiokia\r\nassign-student#12S21002#Antiokia\r\nassign-student#12S21003#Antiokia\r\nassign-student#12S21004#Antiokia\r\nassign-student#12S21006#Pniel\r\nassign-student#12S21007#Pniel\r\nassign-student#12S21008#Antiokia\r\nassign-student#12S21009#Antiokia\r\nassign-student#12S21010#Antiokia\r\nassign-student#12S21011#Antiokia\r\nmove-student#12S21001#Mahanaim\r\nmove-student#12S21007#Nazaret\r\nmove-student#12S21007#Kapernaum\r\nstudent-print-all-detail\r\ndorm-print-all-detail\r\n---\r\n
        expected-output: 12S21001|Dhino Turnip|2021|male\r\n12S21002|Marudut Tampubolon|2021|male\r\n12S21003|Jusas
          Tampubolon|2021|male\r\n12S21004|Estomihi pangaribuan|2021|male\r\n12S21006|Weny
          Sitinjak|2021|female\r\n12S21007|Dame Sitinjak|2021|female\r\n12S21008|Tuani
          Manurung|2021|male\r\n12S21009|Mikhael Pakpahan|2021|male\r\n12S21010|Bobby
          Siagian|2021|male\r\n12S21011|Aldi Simamora|2021|male\r\n12S21007|Dame Sitinjak|2021|female\r\n12S21008|Tuani
          Manurung|2021|male\r\n12S21009|Mikhael Pakpahan|2021|male\r\n12S21010|Bobby
          Siagian|2021|male\r\n12S21011|Aldi Simamora|2021|male\r\n12S21008|Tuani
          Manurung|2021|male\r\n12S21007|Dame Sitinjak|2021|female\r\nAntiokia|5|male\r\nMamre|5|male\r\nSilo|5|male\r\nMahanaim|5|male\r\nNazaret|5|male\r\nPniel|20|female\r\nKapernaum|20|male\r\nPniel|20|female\r\nKapernaum|20|male\r\nPniel|20|female\r\nKapernaum|20|male\r\n12S21001|Dhino
          Turnip|2021|male|Mahanaim\r\n12S21002|Marudut Tampubolon|2021|male|Antiokia\r\n12S21003|Jusas
          Tampubolon|2021|male|Antiokia\r\n12S21004|Estomihi pangaribuan|2021|male|Antiokia\r\n12S21006|Weny
          Sitinjak|2021|female|Pniel\r\n12S21007|Dame Sitinjak|2021|female|Pniel\r\n12S21008|Tuani
          Manurung|2021|male|Antiokia\r\n12S21009|Mikhael Pakpahan|2021|male|unassigned\r\n12S21010|Bobby
          Siagian|2021|male|unassigned\r\n12S21011|Aldi Simamora|2021|male|unassigned\r\n12S21007|Dame
          Sitinjak|2021|female|unassigned\r\n12S21008|Tuani Manurung|2021|male|unassigned\r\n12S21009|Mikhael
          Pakpahan|2021|male|unassigned\r\n12S21010|Bobby Siagian|2021|male|unassigned\r\n12S21011|Aldi
          Simamora|2021|male|unassigned\r\n12S21008|Tuani Manurung|2021|male|unassigned\r\n12S21007|Dame
          Sitinjak|2021|female|unassigned\r\n12S21009|Mikhael Pakpahan|2021|male|unassigned\r\n12S21010|Bobby
          Siagian|2021|male|unassigned\r\n12S21011|Aldi Simamora|2021|male|unassigned\r\nAntiokia|5|male|4\r\nMamre|5|male|0\r\nSilo|5|male|0\r\nMahanaim|5|male|1\r\nNazaret|5|male|0\r\nPniel|20|female|2\r\nKapernaum|20|male|0\r\nPniel|20|female|0\r\nKapernaum|20|male|0\r\nPniel|20|female|0\r\nKapernaum|20|male|0\r\n
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: t10&#45;02&#45;03
      id: t10-45-02-45-03
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t10&#45;02&#45;03
        setup-command: make compile
        command: make -s test_02
        input: student-add#12S21008#Tuani Manurung#2021#male\r\nstudent-add#12S21009#Mikhael
          Pakpahan#2021#male\r\nstudent-add#12S21010#Bobby Siagian#2021#male\r\nstudent-add#12S21011#Aldi
          Simamora#2021#male\r\ndorm-add#Kapernaum#20#male\r\ndorm-add#Pniel#20#female\r\nstudent-add#12S21007#Dame
          Sitinjak#2021#female\r\nassign-student#12S21001#Antiokia\r\nassign-student#12S21002#Antiokia\r\nassign-student#12S21003#Antiokia\r\nassign-student#12S21004#Antiokia\r\nassign-student#12S21006#Pniel\r\nassign-student#12S21007#Pniel\r\nassign-student#12S21008#Antiokia\r\nassign-student#12S21009#Antiokia\r\nassign-student#12S21010#Antiokia\r\nassign-student#12S21011#Antiokia\r\nmove-student#12S21009#Nazaret\r\nmove-student#12S21010#Nazaret\r\nmove-student#12S21011#Nazaret\r\nmove-student#12S21001#Mahanaim\r\nmove-student#12S21007#Nazaret\r\nmove-student#12S21007#Kapernaum\r\nstudent-print-all-detail\r\ndorm-print-all-detail\r\n---\r\n
        expected-output: 12S21001|Dhino Turnip|2021|male|Mahanaim\r\n12S21002|Marudut
          Tampubolon|2021|male|Antiokia\r\n12S21003|Jusas Tampubolon|2021|male|Antiokia\r\n12S21004|Estomihi
          pangaribuan|2021|male|Antiokia\r\n12S21006|Weny Sitinjak|2021|female|Pniel\r\n12S21007|Dame
          Sitinjak|2021|female|Pniel\r\n12S21008|Tuani Manurung|2021|male|Antiokia\r\n12S21009|Mikhael
          Pakpahan|2021|male|Nazaret\r\n12S21010|Bobby Siagian|2021|male|Nazaret\r\n12S21011|Aldi
          Simamora|2021|male|Nazaret\r\n12S21007|Dame Sitinjak|2021|female|unassigned\r\n12S21008|Tuani
          Manurung|2021|male|unassigned\r\n12S21009|Mikhael Pakpahan|2021|male|unassigned\r\n12S21010|Bobby
          Siagian|2021|male|unassigned\r\n12S21011|Aldi Simamora|2021|male|unassigned\r\n12S21008|Tuani
          Manurung|2021|male|unassigned\r\n12S21007|Dame Sitinjak|2021|female|unassigned\r\n12S21009|Mikhael
          Pakpahan|2021|male|unassigned\r\n12S21010|Bobby Siagian|2021|male|unassigned\r\n12S21011|Aldi
          Simamora|2021|male|unassigned\r\n12S21008|Tuani Manurung|2021|male|unassigned\r\n12S21009|Mikhael
          Pakpahan|2021|male|unassigned\r\n12S21010|Bobby Siagian|2021|male|unassigned\r\n12S21011|Aldi
          Simamora|2021|male|unassigned\r\n12S21007|Dame Sitinjak|2021|female|unassigned\r\nAntiokia|5|male|4\r\nMamre|5|male|0\r\nSilo|5|male|0\r\nMahanaim|5|male|1\r\nNazaret|5|male|3\r\nPniel|20|female|2\r\nKapernaum|20|male|0\r\nPniel|20|female|0\r\nKapernaum|20|male|0\r\nPniel|20|female|0\r\nKapernaum|20|male|0\r\nKapernaum|20|male|0\r\nPniel|20|female|0\r\n
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T10-45-01-45-01_RESULTS: "${{steps.t10-45-01-45-01.outputs.result}}"
        T10-45-01-45-02_RESULTS: "${{steps.t10-45-01-45-02.outputs.result}}"
        T10-45-02-45-01_RESULTS: "${{steps.t10-45-02-45-01.outputs.result}}"
        T10-45-02-45-02_RESULTS: "${{steps.t10-45-02-45-02.outputs.result}}"
        T10-45-02-45-03_RESULTS: "${{steps.t10-45-02-45-03.outputs.result}}"
      with:
        runners: t10-45-01-45-01,t10-45-01-45-02,t10-45-02-45-01,t10-45-02-45-02,t10-45-02-45-03
